'use strict';

/* Controllers */

function PlatesListCtrl($scope) {
    $scope.getMapLink = function (area, region) {
        var location = ['Polska', region, name].join(', ');
        location = encodeURIComponent(location);
        return 'http://maps.google.com/?q=' + location;
    };

    $scope.areas = [
    {code: 'BI', name: 'Białystok', region: 'województwo podlaskie', isCapital: 'capital', wiki: 'http://pl.wikipedia.org/wiki/Bia%C5%82ystok'},
    {code: 'BLM', name: 'Łomża powiat', region: 'województwo podlaskie', wiki: 'http://pl.wikipedia.org/wiki/Powiat_%C5%82om%C5%BCy%C5%84ski'},
    {code: 'BL', name: 'Łomża miasto', region: 'województwo podlaskie', wiki: 'http://pl.wikipedia.org/wiki/%C5%81om%C5%BCa'},
    {code: 'BMN', name: 'Mońki', region: 'województwo podlaskie', wiki: 'http://pl.wikipedia.org/wiki/Mo%C5%84ki'},
    {code: 'BS', name: 'Suwałki miasto', region: 'województwo podlaskie', wiki: 'http://pl.wikipedia.org/wiki/Suwa%C5%82ki'},
    {code: 'BSE', name: 'Sejny', region: 'województwo podlaskie', wiki: 'http://pl.wikipedia.org/wiki/Sejny'},
    {code: 'BAU', name: 'Augustów', region: 'województwo podlaskie', wiki: 'http://pl.wikipedia.org/wiki/August%C3%B3w'},
    {code: 'BSI', name: 'Siemiatycze', region: 'województwo podlaskie', wiki: 'http://pl.wikipedia.org/wiki/Siemiatycze'},
    {code: 'BBI', name: 'Bielsk Podlaski', region: 'województwo podlaskie', wiki: 'http://pl.wikipedia.org/wiki/Bielsk_Podlaski'},
    {code: 'BSK', name: 'Sokółka', region: 'województwo podlaskie', wiki: 'http://pl.wikipedia.org/wiki/Sok%C3%B3%C5%82ka'},
    {code: 'BGR', name: 'Grajewo', region: 'województwo podlaskie', wiki: 'http://pl.wikipedia.org/wiki/Grajewo'},
    {code: 'BSU', name: 'Suwałki powiat', region: 'województwo podlaskie', wiki: 'http://pl.wikipedia.org/wiki/Powiat_suwalski'},
    {code: 'BHA', name: 'Hajnówka', region: 'województwo podlaskie', wiki: 'http://pl.wikipedia.org/wiki/Hajn%C3%B3wka'},
    {code: 'BWM', name: 'Wysokie Mazowieckie', region: 'województwo podlaskie', wiki: 'http://pl.wikipedia.org/wiki/Wysokie_Mazowieckie'},
    {code: 'BIA', name: 'Białystok powiat', region: 'województwo podlaskie', wiki: 'http://pl.wikipedia.org/wiki/Powiat_bia%C5%82ostocki'},
    {code: 'BZA', name: 'Zambrów', region: 'województwo podlaskie', wiki: 'http://pl.wikipedia.org/wiki/Zambr%C3%B3w'},
    {code: 'BKL', name: 'Kolno', region: 'województwo podlaskie', wiki: 'http://pl.wikipedia.org/wiki/Kolno'},
    {code: 'CB', name: 'Bydgoszcz', region: 'województwo kujawsko-pomorskie', isCapital: 'capital', wiki: 'http://pl.wikipedia.org/wiki/Bydgoszcz'},
    {code: 'CMG', name: 'Mogilno', region: 'województwo kujawsko-pomorskie', wiki: 'http://pl.wikipedia.org/wiki/Mogilno'},
    {code: 'CG', name: 'Grudziądz miasto', region: 'województwo kujawsko-pomorskie', wiki: 'http://pl.wikipedia.org/wiki/Grudzi%C4%85dz'},
    {code: 'CNA', name: 'Nakło n. Notecią', region: 'województwo kujawsko-pomorskie', wiki: 'http://pl.wikipedia.org/wiki/Nak%C5%82o_nad_Noteci%C4%85'},
    {code: 'CT', name: 'Toruń', region: 'województwo kujawsko-pomorskie', isCapital: 'capital', wiki: 'http://pl.wikipedia.org/wiki/Toru%C5%84'},
    {code: 'CRA', name: 'Radziejów', region: 'województwo kujawsko-pomorskie', wiki: 'http://pl.wikipedia.org/wiki/Radziej%C3%B3w'},
    {code: 'CW', name: 'Włocławek miasto', region: 'województwo kujawsko-pomorskie', wiki: 'http://pl.wikipedia.org/wiki/W%C5%82oc%C5%82awek'},
    {code: 'CRY', name: 'Rypin', region: 'województwo kujawsko-pomorskie', wiki: 'http://pl.wikipedia.org/wiki/Rypin'},
    {code: 'CAL', name: 'Aleksandrów Kujawski', region: 'województwo kujawsko-pomorskie', wiki: 'http://pl.wikipedia.org/wiki/Aleksandr%C3%B3w_Kujawski'},
    {code: 'CSE', name: 'Sępólno Krajeńskie', region: 'województwo kujawsko-pomorskie', wiki: 'http://pl.wikipedia.org/wiki/S%C4%99p%C3%B3lno_Kraje%C5%84skie'},
    {code: 'CBR', name: 'Brodnica', region: 'województwo kujawsko-pomorskie', wiki: 'http://pl.wikipedia.org/wiki/Brodnica'},
    {code: 'CSW', name: 'Świecie', region: 'województwo kujawsko-pomorskie', wiki: 'http://pl.wikipedia.org/wiki/%C5%9Awiecie'},
    {code: 'CBY', name: 'Bydgoszcz powiat', region: 'województwo kujawsko-pomorskie', wiki: 'http://pl.wikipedia.org/wiki/Powiat_bydgoski'},
    {code: 'CTR', name: 'Toruń powiat', region: 'województwo kujawsko-pomorskie', wiki: 'http://pl.wikipedia.org/wiki/Powiat_toru%C5%84ski'},
    {code: 'CCH', name: 'Chełmno', region: 'województwo kujawsko-pomorskie', wiki: 'http://pl.wikipedia.org/wiki/Che%C5%82mno'},
    {code: 'CTU', name: 'Tuchola', region: 'województwo kujawsko-pomorskie', wiki: 'http://pl.wikipedia.org/wiki/Tuchola'},
    {code: 'CGD', name: 'Golub-Dobrzyń', region: 'województwo kujawsko-pomorskie', wiki: 'http://pl.wikipedia.org/wiki/Golub-Dobrzy%C5%84'},
    {code: 'CWA', name: 'Wąbrzeźno', region: 'województwo kujawsko-pomorskie', wiki: 'http://pl.wikipedia.org/wiki/W%C4%85brze%C5%BAno'},
    {code: 'CGR', name: 'Grudziądz powiat', region: 'województwo kujawsko-pomorskie', wiki: 'http://pl.wikipedia.org/wiki/Powiat_grudzi%C4%85dzki'},
    {code: 'CWL', name: 'Włocławek powiat', region: 'województwo kujawsko-pomorskie', wiki: 'http://pl.wikipedia.org/wiki/Powiat_w%C5%82oc%C5%82awski'},
    {code: 'CIN', name: 'Inowrocław', region: 'województwo kujawsko-pomorskie', wiki: 'http://pl.wikipedia.org/wiki/Inowroc%C5%82aw'},
    {code: 'CZN', name: 'Żnin', region: 'województwo kujawsko-pomorskie', wiki: 'http://pl.wikipedia.org/wiki/%C5%BBnin'},
    {code: 'CLI', name: 'Lipno', region: 'województwo kujawsko-pomorskie', wiki: 'http://pl.wikipedia.org/wiki/Lipno'},
    {code: 'DB', name: 'Wałbrzych miasto', region: 'województwo dolnośląskie', wiki: 'http://pl.wikipedia.org/wiki/Wa%C5%82brzych'},
    {code: 'DLU', name: 'Lubin', region: 'województwo dolnośląskie', wiki: 'http://pl.wikipedia.org/wiki/Lubin'},
    {code: 'DJ', name: 'Jelenia Góra miasto', region: 'województwo dolnośląskie', wiki: 'http://pl.wikipedia.org/wiki/Jelenia_G%C3%B3ra'},
    {code: 'DLW', name: 'Lwówek', region: 'województwo dolnośląskie', wiki: 'http://pl.wikipedia.org/wiki/Lw%C3%B3wek'},
    {code: 'DL', name: 'Legnica miasto', region: 'województwo dolnośląskie', wiki: 'http://pl.wikipedia.org/wiki/Legnica'},
    {code: 'DMI', name: 'Milicz', region: 'województwo dolnośląskie', wiki: 'http://pl.wikipedia.org/wiki/Milicz'},
    {code: 'DW', name: 'Wrocław', region: 'województwo dolnośląskie', isCapital: 'capital', wiki: 'http://pl.wikipedia.org/wiki/Wroc%C5%82aw'},
    {code: 'DOA', name: 'Oława', region: 'województwo dolnośląskie', wiki: 'http://pl.wikipedia.org/wiki/O%C5%82awa'},
    {code: 'DBA', name: 'Wałbrzych powiat', region: 'województwo dolnośląskie', wiki: 'http://pl.wikipedia.org/wiki/Powiat_wa%C5%82brzyski'},
    {code: 'DOL', name: 'Oleśnica', region: 'województwo dolnośląskie', wiki: 'http://pl.wikipedia.org/wiki/Ole%C5%9Bnica'},
    {code: 'DBL', name: 'Bolesławiec', region: 'województwo dolnośląskie', wiki: 'http://pl.wikipedia.org/wiki/Boles%C5%82awiec'},
    {code: 'DPL', name: 'Polkowice', region: 'województwo dolnośląskie', wiki: 'http://pl.wikipedia.org/wiki/Polkowice'},
    {code: 'DDZ', name: 'Dzierżoniów', region: 'województwo dolnośląskie', wiki: 'http://pl.wikipedia.org/wiki/Dzier%C5%BConi%C3%B3w'},
    {code: 'DSR', name: 'Środa Śl.', region: 'województwo dolnośląskie', wiki: 'http://pl.wikipedia.org/wiki/%C5%9Aroda_%C5%9Al%C4%85ska'},
    {code: 'DGL', name: 'Głogów', region: 'województwo dolnośląskie', wiki: 'http://pl.wikipedia.org/wiki/G%C5%82og%C3%B3w'},
    {code: 'DST', name: 'Strzelin', region: 'województwo dolnośląskie', wiki: 'http://pl.wikipedia.org/wiki/Strzelin'},
    {code: 'DGR', name: 'Góra', region: 'województwo dolnośląskie', wiki: 'http://pl.wikipedia.org/wiki/G%C3%B3ra_(wojew%C3%B3dztwo_dolno%C5%9Bl%C4%85skie)'},
    {code: 'DSW', name: 'Świdnica', region: 'województwo dolnośląskie', wiki: 'http://pl.wikipedia.org/wiki/%C5%9Awidnica'},
    {code: 'DJA', name: 'Jawor', region: 'województwo dolnośląskie', wiki: 'http://pl.wikipedia.org/wiki/Jawor_(miasto)'},
    {code: 'DTR', name: 'Trzebnica', region: 'województwo dolnośląskie', wiki: 'http://pl.wikipedia.org/wiki/Trzebnica'},
    {code: 'DJE', name: 'Jelenia Góra powiat', region: 'województwo dolnośląskie', wiki: 'http://pl.wikipedia.org/wiki/Powiat_jeleniog%C3%B3rski'},
    {code: 'DWL', name: 'Wołów', region: 'województwo dolnośląskie', wiki: 'http://pl.wikipedia.org/wiki/Wo%C5%82%C3%B3w'},
    {code: 'DKA', name: 'Kamienna Góra', region: 'województwo dolnośląskie', wiki: 'http://pl.wikipedia.org/wiki/Kamienna_G%C3%B3ra'},
    {code: 'DWR', name: 'Wrocław powiat', region: 'województwo dolnośląskie', wiki: 'http://pl.wikipedia.org/wiki/Powiat_wroc%C5%82awski'},
    {code: 'DKL', name: 'Kłodzko', region: 'województwo dolnośląskie', wiki: 'http://pl.wikipedia.org/wiki/K%C5%82odzko'},
    {code: 'DZA', name: 'Ząbkowice', region: 'województwo dolnośląskie', wiki: 'http://pl.wikipedia.org/wiki/Z%C4%85bkowice'},
    {code: 'DLB', name: 'Lubań', region: 'województwo dolnośląskie', wiki: 'http://pl.wikipedia.org/wiki/Luba%C5%84_(wojew%C3%B3dztwo_dolno%C5%9Bl%C4%85skie)'},
    {code: 'DZG', name: 'Zgorzelec', region: 'województwo dolnośląskie', wiki: 'http://pl.wikipedia.org/wiki/Zgorzelec'},
    {code: 'DLE', name: 'Legnica powiat', region: 'województwo dolnośląskie', wiki: 'http://pl.wikipedia.org/wiki/Powiat_legnicki'},
    {code: 'DZL', name: 'Złotoryja', region: 'województwo dolnośląskie', wiki: 'http://pl.wikipedia.org/wiki/Z%C5%82otoryja'},
    {code: 'EL', name: 'Łódź', region: 'województwo łódzkie', isCapital: 'capital', wiki: 'http://pl.wikipedia.org/wiki/%C5%81%C3%B3d%C5%BA'},
    {code: 'EPD', name: 'Poddębice', region: 'województwo łódzkie', wiki: 'http://pl.wikipedia.org/wiki/Podd%C4%99bice'},
    {code: 'EP', name: 'Piotrków Tryb. miasto', region: 'województwo łódzkie', wiki: 'http://pl.wikipedia.org/wiki/Piotrk%C3%B3w_Trybunalski'},
    {code: 'EPI', name: 'Piotrków Tryb. powiat', region: 'województwo łódzkie', wiki: 'http://pl.wikipedia.org/wiki/Powiat_piotrkowski'},
    {code: 'ES', name: 'Skierniewice miasto', region: 'województwo łódzkie', wiki: 'http://pl.wikipedia.org/wiki/Skierniewice'},
    {code: 'EPJ', name: 'Pajęczno', region: 'województwo łódzkie', wiki: 'http://pl.wikipedia.org/wiki/Paj%C4%99czno'},
    {code: 'EBE', name: 'Bełchatów', region: 'województwo łódzkie', wiki: 'http://pl.wikipedia.org/wiki/Be%C5%82chat%C3%B3w'},
    {code: 'ERA', name: 'Radomsko', region: 'województwo łódzkie', wiki: 'http://pl.wikipedia.org/wiki/Radomsko'},
    {code: 'EBR', name: 'Brzeziny', region: 'województwo łódzkie', wiki: 'http://pl.wikipedia.org/wiki/Brzeziny'},
    {code: 'ERW', name: 'Rawa Mazowiecka', region: 'województwo łódzkie', wiki: 'http://pl.wikipedia.org/wiki/Rawa_Mazowiecka'},
    {code: 'EKU', name: 'Kutno', region: 'województwo łódzkie', wiki: 'http://pl.wikipedia.org/wiki/Kutno'},
    {code: 'ESI', name: 'Sieradz', region: 'województwo łódzkie', wiki: 'http://pl.wikipedia.org/wiki/Sieradz'},
    {code: 'ELA', name: 'Łask', region: 'województwo łódzkie', wiki: 'http://pl.wikipedia.org/wiki/%C5%81ask'},
    {code: 'ESK', name: 'Skierniewice powiat', region: 'województwo łódzkie', wiki: 'http://pl.wikipedia.org/wiki/Powiat_skierniewicki'},
    {code: 'ELC', name: 'Łowicz', region: 'województwo łódzkie', wiki: 'http://pl.wikipedia.org/wiki/%C5%81owicz'},
    {code: 'ETM', name: 'Tomaszów Mazowiecki', region: 'województwo łódzkie', wiki: 'http://pl.wikipedia.org/wiki/Tomasz%C3%B3w_Mazowiecki'},
    {code: 'ELE', name: 'Łęczyca', region: 'województwo łódzkie', wiki: 'http://pl.wikipedia.org/wiki/%C5%81%C4%99czyca'},
    {code: 'EWE', name: 'Wieruszów', region: 'województwo łódzkie', wiki: 'http://pl.wikipedia.org/wiki/Wierusz%C3%B3w'},
    {code: 'ELW', name: 'Łódź powiat', region: 'województwo łódzkie', wiki: 'http://pl.wikipedia.org/wiki/Powiat_%C5%82%C3%B3dzki'},
    {code: 'EWI', name: 'Wieluń', region: 'województwo łódzkie', wiki: 'http://pl.wikipedia.org/wiki/Wielu%C5%84'},
    {code: 'EOP', name: 'Opoczno', region: 'województwo łódzkie', wiki: 'http://pl.wikipedia.org/wiki/Opoczno'},
    {code: 'EZD', name: 'Zduńska Wola', region: 'województwo łódzkie', wiki: 'http://pl.wikipedia.org/wiki/Zdu%C5%84ska_Wola'},
    {code: 'EPA', name: 'Pabianice', region: 'województwo łódzkie', wiki: 'http://pl.wikipedia.org/wiki/Zdu%C5%84ska_Wola'},
    {code: 'EZG', name: 'Zgierz', region: 'województwo łódzkie', wiki: 'http://pl.wikipedia.org/wiki/Zgierz'},
    {code: 'FG', name: 'Gorzów Wlkp.', region: 'województwo lubuskie', isCapital: 'capital', wiki: 'http://pl.wikipedia.org/wiki/Gorz%C3%B3w_Wielkopolski'},
    {code: 'FSL', name: 'Słubice', region: 'województwo lubuskie', wiki: 'http://pl.wikipedia.org/wiki/S%C5%82ubice'},
    {code: 'FZ', name: 'Zielona Góra', region: 'województwo lubuskie', isCapital: 'capital', wiki: 'http://pl.wikipedia.org/wiki/Zielona_G%C3%B3ra'},
    {code: 'FSU', name: 'Sulęcin', region: 'województwo lubuskie', wiki: 'http://pl.wikipedia.org/wiki/Sul%C4%99cin'},
    {code: 'FGW', name: 'Gorzów Wlkp. powiat', region: 'województwo lubuskie', wiki: 'http://pl.wikipedia.org/wiki/Powiat_gorzowski'},
    {code: 'FSW', name: 'Świebodzin', region: 'województwo lubuskie', wiki: 'http://pl.wikipedia.org/wiki/%C5%9Awiebodzin'},
    {code: 'FKR', name: 'Krosno Odrzańskie', region: 'województwo lubuskie', wiki: 'http://pl.wikipedia.org/wiki/Krosno_Odrza%C5%84skie'},
    {code: 'FWS', name: 'Wschowa', region: 'województwo lubuskie', wiki: 'http://pl.wikipedia.org/wiki/Wschowa'},
    {code: 'FMI', name: 'Międzyrzecz', region: 'województwo lubuskie', wiki: 'http://pl.wikipedia.org/wiki/Mi%C4%99dzyrzecz'},
    {code: 'FZA', name: 'Żary', region: 'województwo lubuskie', wiki: 'http://pl.wikipedia.org/wiki/%C5%BBary'},
    {code: 'FNW', name: 'Nowa Sól', region: 'województwo lubuskie', wiki: 'http://pl.wikipedia.org/wiki/Nowa_S%C3%B3l'},
    {code: 'FZG', name: 'Żagań', region: 'województwo lubuskie', wiki: 'http://pl.wikipedia.org/wiki/%C5%BBaga%C5%84'},
    {code: 'FSD', name: 'Strzelce Krajeńskie', region: 'województwo lubuskie', wiki: 'http://pl.wikipedia.org/wiki/Strzelce_Kraje%C5%84skie'},
    {code: 'FZI', name: 'Zielona Góra powiat', region: 'województwo lubuskie', wiki: 'http://pl.wikipedia.org/wiki/Powiat_zielonog%C3%B3rski'},
    {code: 'GA', name: 'Gdynia', region: 'województwo pomorskie', wiki: 'http://pl.wikipedia.org/wiki/Gdynia'},
    {code: 'GLE', name: 'Lębork', region: 'województwo pomorskie', wiki: 'http://pl.wikipedia.org/wiki/L%C4%99bork'},
    {code: 'GD', name: 'Gdańsk', region: 'województwo pomorskie', isCapital: 'capital', wiki: 'http://pl.wikipedia.org/wiki/Gda%C5%84sk'},
    {code: 'GMB', name: 'Malbork', region: 'województwo pomorskie', wiki: 'http://pl.wikipedia.org/wiki/Malbork'},
    {code: 'GS', name: 'Słupsk miasto', region: 'województwo pomorskie', wiki: 'http://pl.wikipedia.org/wiki/S%C5%82upsk'},
    {code: 'GND', name: 'Nowy Dwór Gdański', region: 'województwo pomorskie', wiki: 'http://pl.wikipedia.org/wiki/Nowy_Dw%C3%B3r_Gda%C5%84ski'},
    {code: 'GBY', name: 'Bytów', region: 'województwo pomorskie', wiki: 'http://pl.wikipedia.org/wiki/Byt%C3%B3w'},
    {code: 'GPU', name: 'Puck', region: 'województwo pomorskie', wiki: 'http://pl.wikipedia.org/wiki/Puck'},
    {code: 'GCH', name: 'Chojnice', region: 'województwo pomorskie', wiki: 'http://pl.wikipedia.org/wiki/Chojnice'},
    {code: 'GSL', name: 'Słupsk powiat', region: 'województwo pomorskie', wiki: 'http://pl.wikipedia.org/wiki/Powiat_s%C5%82upski'},
    {code: 'GCZ', name: 'Człuchów', region: 'województwo pomorskie', wiki: 'http://pl.wikipedia.org/wiki/Cz%C5%82uch%C3%B3w'},
    {code: 'GSP', name: 'Sopot', region: 'województwo pomorskie', wiki: 'http://pl.wikipedia.org/wiki/Sopot'},
    {code: 'GDA', name: 'Pruszcz Gdański', region: 'województwo pomorskie', wiki: 'http://pl.wikipedia.org/wiki/Pruszcz_Gda%C5%84ski'},
    {code: 'GST', name: 'Starogard Gdański', region: 'województwo pomorskie', wiki: 'http://pl.wikipedia.org/wiki/Starogard_Gda%C5%84ski'},
    {code: 'GKA', name: 'Kartuzy', region: 'województwo pomorskie', wiki: 'http://pl.wikipedia.org/wiki/Kartuzy'},
    {code: 'GSZ', name: 'Sztum', region: 'województwo pomorskie', wiki: 'http://pl.wikipedia.org/wiki/Sztum'},
    {code: 'GKS', name: 'Kościerzyna', region: 'województwo pomorskie', wiki: 'http://pl.wikipedia.org/wiki/Ko%C5%9Bcierzyna'},
    {code: 'GTC', name: 'Tczew', region: 'województwo pomorskie', wiki: 'http://pl.wikipedia.org/wiki/Tczew'},
    {code: 'GKW', name: 'Kwidzyn', region: 'województwo pomorskie', wiki: 'http://pl.wikipedia.org/wiki/Kwidzyn'},
    {code: 'GWE', name: 'Wejherowo', region: 'województwo pomorskie', wiki: 'http://pl.wikipedia.org/wiki/Wejherowo'},
    {code: 'KN', name: 'Nowy Sącz miasto', region: 'województwo małopolskie', wiki: 'http://pl.wikipedia.org/wiki/Nowy_S%C4%85cz'},
    {code: 'KNS', name: 'Nowy Sącz powiat', region: 'województwo małopolskie', wiki: 'http://pl.wikipedia.org/wiki/Powiat_nowos%C4%85decki'},
    {code: 'KR', name: 'Kraków', region: 'województwo małopolskie', isCapital: 'capital', wiki: 'http://pl.wikipedia.org/wiki/Krak%C3%B3w'},
    {code: 'KNT', name: 'Nowy Targ', region: 'województwo małopolskie', wiki: 'http://pl.wikipedia.org/wiki/Nowy_Targ'},
    {code: 'KT', name: 'Tarnów miasto', region: 'województwo małopolskie', wiki: 'http://pl.wikipedia.org/wiki/Tarn%C3%B3w'},
    {code: 'KOL', name: 'Olkusz', region: 'województwo małopolskie', wiki: 'http://pl.wikipedia.org/wiki/Olkusz'},
    {code: 'KBC', name: 'Bochnia', region: 'województwo małopolskie', wiki: 'http://pl.wikipedia.org/wiki/Bochnia'},
    {code: 'KOS', name: 'Oświęcim', region: 'województwo małopolskie', wiki: 'http://pl.wikipedia.org/wiki/O%C5%9Bwi%C4%99cim'},
    {code: 'KBR', name: 'Brzesko', region: 'województwo małopolskie', wiki: 'http://pl.wikipedia.org/wiki/Brzesko'},
    {code: 'KPR', name: 'Proszowice', region: 'województwo małopolskie', wiki: 'http://pl.wikipedia.org/wiki/Proszowice'},
    {code: 'KCH', name: 'Chrzanów', region: 'województwo małopolskie', wiki: 'http://pl.wikipedia.org/wiki/Chrzan%C3%B3w'},
    {code: 'KRA', name: 'Kraków powiat', region: 'województwo małopolskie', wiki: 'http://pl.wikipedia.org/wiki/Powiat_krakowski'},
    {code: 'KDA', name: 'Dąbrowa Tarnowska', region: 'województwo małopolskie', wiki: 'http://pl.wikipedia.org/wiki/D%C4%85browa_Tarnowska'},
    {code: 'KSU', name: 'Sucha Beskidzka', region: 'województwo małopolskie', wiki: 'http://pl.wikipedia.org/wiki/Sucha_Beskidzka'},
    {code: 'KGR', name: 'Gorlice', region: 'województwo małopolskie', wiki: 'http://pl.wikipedia.org/wiki/Sucha_Beskidzka'},
    {code: 'KTA', name: 'Tarnów powiat', region: 'województwo małopolskie', wiki: 'http://pl.wikipedia.org/wiki/Powiat_tarnowski'},
    {code: 'KLI', name: 'Limanowa', region: 'województwo małopolskie', wiki: 'http://pl.wikipedia.org/wiki/Limanowa'},
    {code: 'KTT', name: 'Zakopane', region: 'województwo małopolskie', wiki: 'http://pl.wikipedia.org/wiki/Zakopane'},
    {code: 'KMI', name: 'Miechów', region: 'województwo małopolskie', wiki: 'http://pl.wikipedia.org/wiki/Miech%C3%B3w'},
    {code: 'KWA', name: 'Wadowice', region: 'województwo małopolskie', wiki: 'http://pl.wikipedia.org/wiki/Wadowice'},
    {code: 'KMY', name: 'Myślenice', region: 'województwo małopolskie', wiki: 'http://pl.wikipedia.org/wiki/My%C5%9Blenice'},
    {code: 'KWI', name: 'Wieliczka', region: 'województwo małopolskie', wiki: 'http://pl.wikipedia.org/wiki/Wieliczka'},
    {code: 'LB', name: 'Biała Podlaska miasto', region: 'województwo lubelskie', wiki: 'http://pl.wikipedia.org/wiki/Bia%C5%82a_Podlaska'},
    {code: 'LLE', name: 'Łęczna', region: 'województwo lubelskie', wiki: 'http://pl.wikipedia.org/wiki/%C5%81%C4%99czna'},
    {code: 'LC', name: 'Chełm miasto', region: 'województwo lubelskie', wiki: 'http://pl.wikipedia.org/wiki/Che%C5%82m'},
    {code: 'LLU', name: 'Łuków', region: 'województwo lubelskie', wiki: 'http://pl.wikipedia.org/wiki/%C5%81uk%C3%B3w'},
    {code: 'LU', name: 'Lublin', region: 'województwo lubelskie', isCapital: 'capital', wiki: 'http://pl.wikipedia.org/wiki/Lublin'},
    {code: 'LOP', name: 'Opole Lubelskie', region: 'województwo lubelskie', wiki: 'http://pl.wikipedia.org/wiki/Opole_Lubelskie'},
    {code: 'LZ', name: 'Zamość miasto', region: 'województwo lubelskie', wiki: 'http://pl.wikipedia.org/wiki/Zamo%C5%9B%C4%87'},
    {code: 'LPA', name: 'Parczew', region: 'województwo lubelskie', wiki: 'http://pl.wikipedia.org/wiki/Parczew'},
    {code: 'LBI', name: 'Biała Podlaska powiat', region: 'województwo lubelskie', wiki: 'http://pl.wikipedia.org/wiki/Powiat_bialski'},
    {code: 'LPU', name: 'Puławy', region: 'województwo lubelskie', wiki: 'http://pl.wikipedia.org/wiki/Pu%C5%82awy'},
    {code: 'LBL', name: 'Biłgoraj', region: 'województwo lubelskie', wiki: 'http://pl.wikipedia.org/wiki/Bi%C5%82goraj'},
    {code: 'LRA', name: 'Radzyń Podlaski', region: 'województwo lubelskie', wiki: 'http://pl.wikipedia.org/wiki/Radzy%C5%84_Podlaski'},
    {code: 'LCH', name: 'Chełm powiat', region: 'województwo lubelskie', wiki: 'http://pl.wikipedia.org/wiki/Powiat_che%C5%82mski'},
    {code: 'LRY', name: 'Ryki', region: 'województwo lubelskie', wiki: 'http://pl.wikipedia.org/wiki/Ryki'},
    {code: 'LHR', name: 'Hrubieszów', region: 'województwo lubelskie', wiki: 'http://pl.wikipedia.org/wiki/Hrubiesz%C3%B3w'},
    {code: 'LSW', name: 'Świdnik', region: 'województwo lubelskie', wiki: 'http://pl.wikipedia.org/wiki/%C5%9Awidnik'},
    {code: 'LJA', name: 'Janów Lubelski', region: 'województwo lubelskie', wiki: 'http://pl.wikipedia.org/wiki/Jan%C3%B3w_Lubelski'},
    {code: 'LTM', name: 'Tomaszów Lubelski', region: 'województwo lubelskie', wiki: 'http://pl.wikipedia.org/wiki/Tomasz%C3%B3w_Lubelski'},
    {code: 'LKR', name: 'Kraśnik', region: 'województwo lubelskie', wiki: 'http://pl.wikipedia.org/wiki/Kra%C5%9Bnik'},
    {code: 'LUB', name: 'Lublin powiat', region: 'województwo lubelskie', wiki: 'http://pl.wikipedia.org/wiki/Powiat_lubelski'},
    {code: 'LKS', name: 'Krasnystaw', region: 'województwo lubelskie', wiki: 'http://pl.wikipedia.org/wiki/Krasnystaw'},
    {code: 'LWL', name: 'Włodawa', region: 'województwo lubelskie', wiki: 'http://pl.wikipedia.org/wiki/W%C5%82odawa'},
    {code: 'LLB', name: 'Lubartów', region: 'województwo lubelskie', wiki: 'http://pl.wikipedia.org/wiki/Lubart%C3%B3w'},
    {code: 'LZA', name: 'Zamość powiat', region: 'województwo lubelskie', wiki: 'http://pl.wikipedia.org/wiki/Powiat_zamojski'},
    {code: 'NE', name: 'Elbląg miasto', region: 'województwo warmińsko-mazurskie', wiki: 'http://pl.wikipedia.org/wiki/Elbl%C4%85g'},
    {code: 'NLI', name: 'Lidzbark Warmiński', region: 'województwo warmińsko-mazurskie', wiki: 'http://pl.wikipedia.org/wiki/Lidzbark_Warmi%C5%84ski'},
    {code: 'NO', name: 'Olsztyn', region: 'województwo warmińsko-mazurskie', isCapital: 'capital', wiki: 'http://pl.wikipedia.org/wiki/Olsztyn'},
    {code: 'NMR', name: 'Mrągowo', region: 'województwo warmińsko-mazurskie', wiki: 'http://pl.wikipedia.org/wiki/Mr%C4%85gowo'},
    {code: 'NBA', name: 'Bartoszyce', region: 'województwo warmińsko-mazurskie', wiki: 'http://pl.wikipedia.org/wiki/Bartoszyce'},
    {code: 'NNI', name: 'Nidzica', region: 'województwo warmińsko-mazurskie', wiki: 'http://pl.wikipedia.org/wiki/Nidzica'},
    {code: 'NBR', name: 'Braniewo', region: 'województwo warmińsko-mazurskie', wiki: 'http://pl.wikipedia.org/wiki/Braniewo'},
    {code: 'NNM', name: 'Nowe Miasto Lub.', region: 'województwo warmińsko-mazurskie', wiki: 'http://pl.wikipedia.org/wiki/Nowe_Miasto_Lubawskie'},
    {code: 'NDZ', name: 'Działdowo', region: 'województwo warmińsko-mazurskie', wiki: 'http://pl.wikipedia.org/wiki/Dzia%C5%82dowo'},
    {code: 'NOE', name: 'Olecko', region: 'województwo warmińsko-mazurskie', wiki: 'http://pl.wikipedia.org/wiki/Olecko'},
    {code: 'NEB', name: 'Elbląg powiat', region: 'województwo warmińsko-mazurskie', wiki: 'http://pl.wikipedia.org/wiki/Powiat_elbl%C4%85ski'},
    {code: 'NOL', name: 'Olsztyn powiat', region: 'województwo warmińsko-mazurskie', wiki: 'http://pl.wikipedia.org/wiki/Powiat_olszty%C5%84ski'},
    {code: 'NEL', name: 'Ełk', region: 'województwo warmińsko-mazurskie', wiki: 'http://pl.wikipedia.org/wiki/Powiat_e%C5%82cki'},
    {code: 'NOS', name: 'Ostróda', region: 'województwo warmińsko-mazurskie', wiki: 'http://pl.wikipedia.org/wiki/Ostr%C3%B3da'},
    {code: 'NGI', name: 'Giżycko', region: 'województwo warmińsko-mazurskie', wiki: 'http://pl.wikipedia.org/wiki/Gi%C5%BCycko'},
    {code: 'NPI', name: 'Pisz', region: 'województwo warmińsko-mazurskie', wiki: 'http://pl.wikipedia.org/wiki/Pisz'},
    {code: 'NGO', name: 'Gołdap', region: 'województwo warmińsko-mazurskie', wiki: 'http://pl.wikipedia.org/wiki/Go%C5%82dap'},
    {code: 'NSZ', name: 'Szczytno', region: 'województwo warmińsko-mazurskie', wiki: 'http://pl.wikipedia.org/wiki/Szczytno'},
    {code: 'NIL', name: 'Iława', region: 'województwo warmińsko-mazurskie', wiki: 'http://pl.wikipedia.org/wiki/I%C5%82awa'},
    {code: 'NWE', name: 'Węgorzewo', region: 'województwo warmińsko-mazurskie', wiki: 'http://pl.wikipedia.org/wiki/W%C4%99gorzewo'},
    {code: 'NKE', name: 'Kętrzyn', region: 'województwo warmińsko-mazurskie', wiki: 'http://pl.wikipedia.org/wiki/K%C4%99trzyn'},
    {code: 'OB', name: 'Brzeg', region: 'województwo opolskie', wiki: 'http://pl.wikipedia.org/wiki/Brzeg_(miasto)'},
    {code: 'ONA', name: 'Namysłów', region: 'województwo opolskie', wiki: 'http://pl.wikipedia.org/wiki/Namys%C5%82%C3%B3w'},
    {code: 'OP', name: 'Opole', region: 'województwo opolskie', isCapital: 'capital', wiki: 'http://pl.wikipedia.org/wiki/Opole'},
    {code: 'ONY', name: 'Nysa', region: 'województwo opolskie', wiki: 'http://pl.wikipedia.org/wiki/Nysa'},
    {code: 'OK', name: 'Kędzierzyn Koźle', region: 'województwo opolskie', wiki: 'http://pl.wikipedia.org/wiki/K%C4%99dzierzyn-Ko%C5%BAle'},
    {code: 'OOL', name: 'Olesno', region: 'województwo opolskie', wiki: 'http://pl.wikipedia.org/wiki/Olesno'},
    {code: 'OGL', name: 'Głubczyce', region: 'województwo opolskie', wiki: 'http://pl.wikipedia.org/wiki/g%C5%82ubczyce'},
    {code: 'OPO', name: 'Opole powiat', region: 'województwo opolskie', wiki: 'http://pl.wikipedia.org/wiki/Powiat_opolski_(wojew%C3%B3dztwo_opolskie)'},
    {code: 'OKL', name: 'Kluczbork', region: 'województwo opolskie', wiki: 'http://pl.wikipedia.org/wiki/Kluczbork'},
    {code: 'OPR', name: 'Prudnik', region: 'województwo opolskie', wiki: 'http://pl.wikipedia.org/wiki/Prudnik'},
    {code: 'OKR', name: 'Krapkowice', region: 'województwo opolskie', wiki: 'http://pl.wikipedia.org/wiki/Krapkowice'},
    {code: 'OST', name: 'Strzelce Opolskie', region: 'województwo opolskie', wiki: 'http://pl.wikipedia.org/wiki/Strzelce_Opolskie'},
    {code: 'PK', name: 'Kalisz miasto', region: 'województwo wielkopolskie', wiki: 'http://pl.wikipedia.org/wiki/Kalisz'},
    {code: 'PLE', name: 'Leszno powiat', region: 'województwo wielkopolskie', wiki: 'http://pl.wikipedia.org/wiki/Powiat_leszczy%C5%84ski'},
    {code: 'PL', name: 'Leszno miasto', region: 'województwo wielkopolskie', wiki: 'http://pl.wikipedia.org/wiki/Leszno'},
    {code: 'PMI', name: 'Międzychód', region: 'województwo wielkopolskie', wiki: 'http://pl.wikipedia.org/wiki/Mi%C4%99dzych%C3%B3d'},
    {code: 'PN', name: 'Konin miasto', region: 'województwo wielkopolskie', wiki: 'http://pl.wikipedia.org/wiki/Konin'},
    {code: 'PNT', name: 'Nowy Tomyśl', region: 'województwo wielkopolskie', wiki: 'http://pl.wikipedia.org/wiki/Nowy_Tomy%C5%9Bl'},
    {code: 'PO', name: 'Poznań', region: 'województwo wielkopolskie', isCapital: 'capital', wiki: 'http://pl.wikipedia.org/wiki/Pozna%C5%84'},
    {code: 'POB', name: 'Oborniki', region: 'województwo wielkopolskie', wiki: 'http://pl.wikipedia.org/wiki/Oborniki'},
    {code: 'PP', name: 'Piła', region: 'województwo wielkopolskie', wiki: 'http://pl.wikipedia.org/wiki/Pi%C5%82a_(miasto)'},
    {code: 'POT', name: 'Ostrzeszów', region: 'województwo wielkopolskie', wiki: 'http://pl.wikipedia.org/wiki/Ostrzesz%C3%B3w'},
    {code: 'PZ', name: 'Poznań powiat', region: 'województwo wielkopolskie', wiki: 'http://pl.wikipedia.org/wiki/Powiat_pozna%C5%84ski'},
    {code: 'POS', name: 'Ostrów Wlkp.', region: 'województwo wielkopolskie', wiki: 'http://pl.wikipedia.org/wiki/Ostr%C3%B3w_Wielkopolski'},
    {code: 'PCH', name: 'Chodzież', region: 'województwo wielkopolskie', wiki: 'http://pl.wikipedia.org/wiki/Chodzie%C5%BC'},
    {code: 'POZ', name: 'Poznań powiat', region: 'województwo wielkopolskie', wiki: 'http://pl.wikipedia.org/wiki/Powiat_pozna%C5%84ski'},
    {code: 'PCT', name: 'Czarnków', region: 'województwo wielkopolskie', wiki: 'http://pl.wikipedia.org/wiki/Czarnk%C3%B3w'},
    {code: 'PPL', name: 'Pleszew', region: 'województwo wielkopolskie', wiki: 'http://pl.wikipedia.org/wiki/Pleszew'},
    {code: 'PGN', name: 'Gniezno', region: 'województwo wielkopolskie', wiki: 'http://pl.wikipedia.org/wiki/Gniezno'},
    {code: 'PRA', name: 'Rawicz', region: 'województwo wielkopolskie', wiki: 'http://pl.wikipedia.org/wiki/Rawicz'},
    {code: 'PGO', name: 'Grodzisk Wlkp.', region: 'województwo wielkopolskie', wiki: 'http://pl.wikipedia.org/wiki/Grodzisk_Wielkopolski'},
    {code: 'PSE', name: 'Śrem', region: 'województwo wielkopolskie', wiki: 'http://pl.wikipedia.org/wiki/%C5%9Arem'},
    {code: 'PGS', name: 'Gostyń', region: 'województwo wielkopolskie', wiki: 'http://pl.wikipedia.org/wiki/Gosty%C5%84'},
    {code: 'PSL', name: 'Słupca', region: 'województwo wielkopolskie', wiki: 'http://pl.wikipedia.org/wiki/S%C5%82upca'},
    {code: 'PJA', name: 'Jarocin', region: 'województwo wielkopolskie', wiki: 'http://pl.wikipedia.org/wiki/Jarocin'},
    {code: 'PSR', name: 'Środa Wlkp.', region: 'województwo wielkopolskie', wiki: 'http://pl.wikipedia.org/wiki/%C5%9Aroda_Wielkopolska'},
    {code: 'PKA', name: 'Kalisz powiat', region: 'województwo wielkopolskie', wiki: 'http://pl.wikipedia.org/wiki/Powiat_kaliski'},
    {code: 'PSZ', name: 'Szamotuły', region: 'województwo wielkopolskie', wiki: 'http://pl.wikipedia.org/wiki/Szamotu%C5%82y'},
    {code: 'PKE', name: 'Kępno', region: 'województwo wielkopolskie', wiki: 'http://pl.wikipedia.org/wiki/K%C4%99pno'},
    {code: 'PTU', name: 'Turek', region: 'województwo wielkopolskie', wiki: 'http://pl.wikipedia.org/wiki/Turek'},
    {code: 'PKL', name: 'Koło', region: 'województwo wielkopolskie', wiki: 'http://pl.wikipedia.org/wiki/Ko%C5%82o_(wojew%C3%B3dztwo_wielkopolskie)'},
    {code: 'PWA', name: 'Wągrowiec', region: 'województwo wielkopolskie', wiki: 'http://pl.wikipedia.org/wiki/W%C4%85growiec'},
    {code: 'PKN', name: 'Konin powiat', region: 'województwo wielkopolskie', wiki: 'http://pl.wikipedia.org/wiki/Powiat_koni%C5%84ski'},
    {code: 'PWL', name: 'Wolsztyn', region: 'województwo wielkopolskie', wiki: 'http://pl.wikipedia.org/wiki/Wolsztyn'},
    {code: 'PKO', name: 'Konin miasto', region: 'województwo wielkopolskie', wiki: 'http://pl.wikipedia.org/wiki/Konin'},
    {code: 'PWR', name: 'Września', region: 'województwo wielkopolskie', wiki: 'http://pl.wikipedia.org/wiki/Wrze%C5%9Bnia'},
    {code: 'PKR', name: 'Krotoszyn', region: 'województwo wielkopolskie', wiki: 'http://pl.wikipedia.org/wiki/Krotoszyn'},
    {code: 'PZL', name: 'Złotów', region: 'województwo wielkopolskie', wiki: 'http://pl.wikipedia.org/wiki/Z%C5%82ot%C3%B3w'},
    {code: 'PKS', name: 'Kościan', region: 'województwo wielkopolskie', wiki: 'http://pl.wikipedia.org/wiki/Ko%C5%9Bcian'},
    {code: 'RK', name: 'Krosno miasto', region: 'województwo podkarpackie', wiki: 'http://pl.wikipedia.org/wiki/Krosno'},
    {code: 'RLS', name: 'Lesko', region: 'województwo podkarpackie', wiki: 'http://pl.wikipedia.org/wiki/Lesko'},
    {code: 'RP', name: 'Przemyśl miasto', region: 'województwo podkarpackie', wiki: 'http://pl.wikipedia.org/wiki/Przemy%C5%9Bl'},
    {code: 'RLU', name: 'Lubaczów', region: 'województwo podkarpackie', wiki: 'http://pl.wikipedia.org/wiki/Lubacz%C3%B3w'},
    {code: 'RT', name: 'Tarnobrzeg miasto', region: 'województwo podkarpackie', wiki: 'http://pl.wikipedia.org/wiki/Tarnobrzeg'},
    {code: 'RMI', name: 'Mielec', region: 'województwo podkarpackie', wiki: 'http://pl.wikipedia.org/wiki/Mielec'},
    {code: 'RZ', name: 'Rzeszów', region: 'województwo podkarpackie', isCapital: 'capital', wiki: 'http://pl.wikipedia.org/wiki/Rzesz%C3%B3w'},
    {code: 'RNI', name: 'Nisko', region: 'województwo podkarpackie', wiki: 'http://pl.wikipedia.org/wiki/Nisko'},
    {code: 'RBI', name: 'Ustrzyki Dolne', region: 'województwo podkarpackie', wiki: 'http://pl.wikipedia.org/wiki/Ustrzyki_Dolne'},
    {code: 'RPR', name: 'Przemyśl powiat', region: 'województwo podkarpackie', wiki: 'http://pl.wikipedia.org/wiki/Powiat_przemyski'},
    {code: 'RBR', name: 'Brzozów', region: 'województwo podkarpackie', wiki: 'http://pl.wikipedia.org/wiki/Brzoz%C3%B3w'},
    {code: 'RPZ', name: 'Przeworsk', region: 'województwo podkarpackie', wiki: 'http://pl.wikipedia.org/wiki/Przeworsk'},
    {code: 'RDE', name: 'Dębica', region: 'województwo podkarpackie', wiki: 'http://pl.wikipedia.org/wiki/D%C4%99bica'},
    {code: 'RRS', name: 'Ropczyce', region: 'województwo podkarpackie', wiki: 'http://pl.wikipedia.org/wiki/Ropczyce'},
    {code: 'RJA', name: 'Jarosław', region: 'województwo podkarpackie', wiki: 'http://pl.wikipedia.org/wiki/Jaros%C5%82aw'},
    {code: 'RSA', name: 'Sanok', region: 'województwo podkarpackie', wiki: 'http://pl.wikipedia.org/wiki/Sanok'},
    {code: 'RJS', name: 'Jasło', region: 'województwo podkarpackie', wiki: 'http://pl.wikipedia.org/wiki/Jas%C5%82o'},
    {code: 'RSR', name: 'Strzyżów', region: 'województwo podkarpackie', wiki: 'http://pl.wikipedia.org/wiki/Strzy%C5%BC%C3%B3w'},
    {code: 'RKL', name: 'Kolbuszowa', region: 'województwo podkarpackie', wiki: 'http://pl.wikipedia.org/wiki/Kolbuszowa'},
    {code: 'RST', name: 'Stalowa Wola', region: 'województwo podkarpackie', wiki: 'http://pl.wikipedia.org/wiki/Stalowa_Wola'},
    {code: 'RKR', name: 'Krosno powiat', region: 'województwo podkarpackie', wiki: 'http://pl.wikipedia.org/wiki/Powiat_kro%C5%9Bnie%C5%84ski_(wojew%C3%B3dztwo_podkarpackie)'},
    {code: 'RTA', name: 'Tarnobrzeg powiat', region: 'województwo podkarpackie', wiki: 'http://pl.wikipedia.org/wiki/Powiat_tarnobrzeski'},
    {code: 'RLA', name: 'Łańcut', region: 'województwo podkarpackie', wiki: 'http://pl.wikipedia.org/wiki/%C5%81a%C5%84cut'},
    {code: 'RZE', name: 'Rzeszów powiat', region: 'województwo podkarpackie', wiki: 'http://pl.wikipedia.org/wiki/Powiat_rzeszowski'},
    {code: 'RLE', name: 'Leżajsk', region: 'województwo podkarpackie', wiki: 'http://pl.wikipedia.org/wiki/Le%C5%BCajsk'},
    {code: 'SB', name: 'Bielsko-Biała miasto', region: 'województwo śląskie', wiki: 'http://pl.wikipedia.org/wiki/Bielsko-Bia%C5%82a'},
    {code: 'SCI', name: 'Cieszyn', region: 'województwo śląskie', wiki: 'http://pl.wikipedia.org/wiki/Cieszyn'},
    {code: 'SC', name: 'Częstochowa miasto', region: 'województwo śląskie', wiki: 'http://pl.wikipedia.org/wiki/Cz%C4%99stochowa'},
    {code: 'SCZ', name: 'Częstochowa powiat', region: 'województwo śląskie', wiki: 'http://pl.wikipedia.org/wiki/Powiat_cz%C4%99stochowski'},
    {code: 'SD', name: 'Dąbrowa Górnicza', region: 'województwo śląskie', wiki: 'http://pl.wikipedia.org/wiki/D%C4%85browa_G%C3%B3rnicza'},
    {code: 'SGL', name: 'Gliwice powiat', region: 'województwo śląskie', wiki: 'http://pl.wikipedia.org/wiki/Powiat_gliwicki'},
    {code: 'SG', name: 'Gliwice miasto', region: 'województwo śląskie', wiki: 'http://pl.wikipedia.org/wiki/Gliwice'},
    {code: 'SJZ', name: 'Jastrzębie Zdrój', region: 'województwo śląskie', wiki: 'http://pl.wikipedia.org/wiki/Jastrz%C4%99bie_Zdr%C3%B3j'},
    {code: 'SH', name: 'Chorzów', region: 'województwo śląskie', wiki: 'http://pl.wikipedia.org/wiki/Chorz%C3%B3w'},
    {code: 'SKL', name: 'Kłobuck', region: 'województwo śląskie', wiki: 'http://pl.wikipedia.org/wiki/K%C5%82obuck'},
    {code: 'SI', name: 'Siemianowice Śląskie', region: 'województwo śląskie', wiki: 'http://pl.wikipedia.org/wiki/Siemianowice_%C5%9Al%C4%85skie'},
    {code: 'SLU', name: 'Lubliniec', region: 'województwo śląskie', wiki: 'http://pl.wikipedia.org/wiki/Lubliniec'},
    {code: 'SJ', name: 'Jaworzno', region: 'województwo śląskie', wiki: 'http://pl.wikipedia.org/wiki/Jaworzno'},
    {code: 'SMI', name: 'Mikołów', region: 'województwo śląskie', wiki: 'http://pl.wikipedia.org/wiki/Miko%C5%82%C3%B3w'},
    {code: 'SK', name: 'Katowice', region: 'województwo śląskie', isCapital: 'capital', wiki: 'http://pl.wikipedia.org/wiki/Katowice'},
    {code: 'SMY', name: 'Myszków', region: 'województwo śląskie', wiki: 'http://pl.wikipedia.org/wiki/Myszk%C3%B3w'},
    {code: 'SL', name: 'Ruda Śląska', region: 'województwo śląskie', wiki: 'http://pl.wikipedia.org/wiki/Ruda_%C5%9Al%C4%85ska'},
    {code: 'SPI', name: 'Piekary Śląskie', region: 'województwo śląskie', wiki: 'http://pl.wikipedia.org/wiki/Piekary_%C5%9Al%C4%85skie'},
    {code: 'SM', name: 'Mysłowice', region: 'województwo śląskie', wiki: 'http://pl.wikipedia.org/wiki/Mys%C5%82owice'},
    {code: 'SPS', name: 'Pszczyna', region: 'województwo śląskie', wiki: 'http://pl.wikipedia.org/wiki/Pszczyna'},
    {code: 'SO', name: 'Sosnowiec', region: 'województwo śląskie', wiki: 'http://pl.wikipedia.org/wiki/Sosnowiec'},
    {code: 'SRB', name: 'Rybnik powiat', region: 'województwo śląskie', wiki: 'http://pl.wikipedia.org/wiki/Powiat_rybnicki'},
    {code: 'SR', name: 'Rybnik miasto', region: 'województwo śląskie', wiki: 'http://pl.wikipedia.org/wiki/Rybnik'},
    {code: 'SRC', name: 'Racibórz', region: 'województwo śląskie', wiki: 'http://pl.wikipedia.org/wiki/Racib%C3%B3rz'},
    {code: 'ST', name: 'Tychy miasto', region: 'województwo śląskie', wiki: 'http://pl.wikipedia.org/wiki/Tychy'},
    {code: 'SRS', name: 'Ruda Śląska', region: 'województwo śląskie', wiki: 'http://pl.wikipedia.org/wiki/Ruda_%C5%9Al%C4%85ska'},
    {code: 'SY', name: 'Bytom', region: 'województwo śląskie', wiki: 'http://pl.wikipedia.org/wiki/Bytom'},
    {code: 'STA', name: 'Tarnowskie Góry', region: 'województwo śląskie', wiki: 'http://pl.wikipedia.org/wiki/Tarnowskie_G%C3%B3ry'},
    {code: 'SW', name: 'Świętochłowice', region: 'województwo śląskie', wiki: 'http://pl.wikipedia.org/wiki/%C5%9Awi%C4%99toch%C5%82owice'},
    {code: 'SWD', name: 'Wodzisław', region: 'województwo śląskie', wiki: 'http://pl.wikipedia.org/wiki/Wodzis%C5%82aw_%C5%9Al%C4%85ski'},
    {code: 'SZ', name: 'Zabrze', region: 'województwo śląskie', wiki: 'http://pl.wikipedia.org/wiki/Zabrze'},
    {code: 'SZA', name: 'Zawiercie', region: 'województwo śląskie', wiki: 'http://pl.wikipedia.org/wiki/Zawiercie'},
    {code: 'SBE', name: 'Będzin', region: 'województwo śląskie', wiki: 'http://pl.wikipedia.org/wiki/B%C4%99dzin'},
    {code: 'SZO', name: 'Żory', region: 'województwo śląskie', wiki: 'http://pl.wikipedia.org/wiki/%C5%BBory'},
    {code: 'SBI', name: 'Bielsko-Biała powiat', region: 'województwo śląskie', wiki: 'http://pl.wikipedia.org/wiki/Powiat_bielski_(wojew%C3%B3dztwo_%C5%9Bl%C4%85skie)'},
    {code: 'SZY', name: 'Żywiec', region: 'województwo śląskie', wiki: 'http://pl.wikipedia.org/wiki/%C5%BBywiec'},
    {code: 'SBL', name: 'Tychy powiat', region: 'województwo śląskie', wiki: 'http://pl.wikipedia.org/wiki/Powiat_tyski'},
    {code: 'TK', name: 'Kielce', region: 'województwo świętokrzyskie', isCapital: 'capital', wiki: 'http://pl.wikipedia.org/wiki/Kielce'},
    {code: 'TOP', name: 'Opatów', region: 'województwo świętokrzyskie', wiki: 'http://pl.wikipedia.org/wiki/Opat%C3%B3w'},
    {code: 'TBU', name: 'Busko', region: 'województwo świętokrzyskie', wiki: 'http://pl.wikipedia.org/wiki/Busko'},
    {code: 'TOS', name: 'Ostrowiec Świętokrzyski', region: 'województwo świętokrzyskie', wiki: 'http://pl.wikipedia.org/wiki/Ostrowiec_%C5%9Awi%C4%99tokrzyski'},
    {code: 'TJE', name: 'Jędrzejów', region: 'województwo świętokrzyskie', wiki: 'http://pl.wikipedia.org/wiki/J%C4%99drzej%C3%B3w'},
    {code: 'TPI', name: 'Pińczów', region: 'województwo świętokrzyskie', wiki: 'http://pl.wikipedia.org/wiki/Pi%C5%84cz%C3%B3w'},
    {code: 'TKA', name: 'Kazimierza Wielka', region: 'województwo świętokrzyskie', wiki: 'http://pl.wikipedia.org/wiki/Kazimierza_Wielka'},
    {code: 'TSA', name: 'Sandomierz', region: 'województwo świętokrzyskie', wiki: 'http://pl.wikipedia.org/wiki/Sandomierz'},
    {code: 'TKI', name: 'Kielce powiat', region: 'województwo świętokrzyskie', wiki: 'http://pl.wikipedia.org/wiki/Powiat_kielecki'},
    {code: 'TSK', name: 'Skarżysko-Kamienna', region: 'województwo świętokrzyskie', wiki: 'http://pl.wikipedia.org/wiki/Skar%C5%BCysko-Kamienna'},
    {code: 'TKN', name: 'Końskie', region: 'województwo świętokrzyskie', wiki: 'http://pl.wikipedia.org/wiki/Ko%C5%84skie'},
    {code: 'TST', name: 'Starachowice', region: 'województwo świętokrzyskie', wiki: 'http://pl.wikipedia.org/wiki/Starachowice'},
    {code: 'TLW', name: 'Włoszczowa', region: 'województwo świętokrzyskie', wiki: 'http://pl.wikipedia.org/wiki/W%C5%82oszczowa'},
    {code: 'TSZ', name: 'Staszów', region: 'województwo świętokrzyskie', wiki: 'http://pl.wikipedia.org/wiki/Stasz%C3%B3w'},
    {code: 'WA', name: 'Warszawa-Białołęka', region: 'województwo mazowieckie', wiki: 'http://pl.wikipedia.org/wiki/Bia%C5%82o%C5%82%C4%99ka'},
    {code: 'WM', name: 'Mińsk Mazowiecki', region: 'województwo mazowieckie', wiki: 'http://pl.wikipedia.org/wiki/Mi%C5%84sk_Mazowiecki'},
    {code: 'WB', name: 'Warszawa-Bemowo', region: 'województwo mazowieckie', wiki: 'http://pl.wikipedia.org/wiki/Bemowo'},
    {code: 'WN', name: 'Warszawa-Ursynów', region: 'województwo mazowieckie', wiki: 'http://pl.wikipedia.org/wiki/Ursyn%C3%B3w'},
    {code: 'WD', name: 'Warszawa-Bielany', region: 'województwo mazowieckie', wiki: 'http://pl.wikipedia.org/wiki/Bielany_(Warszawa)'},
    {code: 'WO', name: 'Ostrołęka miasto', region: 'województwo mazowieckie', wiki: 'http://pl.wikipedia.org/wiki/Ostro%C5%82%C4%99ka'},
    {code: 'WE', name: 'Warszawa-Mokotów', region: 'województwo mazowieckie', wiki: 'http://pl.wikipedia.org/wiki/Mokot%C3%B3w'},
    {code: 'WP', name: 'Płock miasto', region: 'województwo mazowieckie', wiki: 'http://pl.wikipedia.org/wiki/P%C5%82ock'},
    {code: 'WF', name: 'Warszawa-Praga Pd.', region: 'województwo mazowieckie', wiki: 'http://pl.wikipedia.org/wiki/Praga_Po%C5%82udnie'},
    {code: 'WR', name: 'Radom miasto', region: 'województwo mazowieckie', wiki: 'http://pl.wikipedia.org/wiki/Radom'},
    {code: 'WG', name: 'Garwolin', region: 'województwo mazowieckie', wiki: 'http://pl.wikipedia.org/wiki/Garwolin'},
    {code: 'WS', name: 'Siedlce miasto', region: 'województwo mazowieckie', wiki: 'http://pl.wikipedia.org/wiki/Siedlce'},
    {code: 'WH', name: 'Warszawa-Praga Pn.', region: 'województwo mazowieckie', wiki: 'http://pl.wikipedia.org/wiki/Praga_P%C3%B3%C5%82noc'},
    {code: 'WT', name: 'Warszawa-Wawer', region: 'województwo mazowieckie', wiki: 'http://pl.wikipedia.org/wiki/Wawer'},
    {code: 'WI', name: 'Warszawa-Śródmieście', region: 'województwo mazowieckie', wiki: 'http://pl.wikipedia.org/wiki/%C5%9Ar%C3%B3dmie%C5%9Bcie_(Warszawa)'},
    {code: 'WU', name: 'Warszawa-Ochota', region: 'województwo mazowieckie', wiki: 'http://pl.wikipedia.org/wiki/Ochota'},
    {code: 'WJ', name: 'Warszawa-Targówek', region: 'województwo mazowieckie', wiki: 'http://pl.wikipedia.org/wiki/Targ%C3%B3wek'},
    {code: 'WY', name: 'Warszawa-Wola', region: 'województwo mazowieckie', wiki: 'http://pl.wikipedia.org/wiki/Wola_(Warszawa)'},
    {code: 'WK', name: 'Warszawa-Ursus', region: 'województwo mazowieckie', wiki: 'http://pl.wikipedia.org/wiki/Ursus_(Warszawa)'},
    {code: 'WX', name: 'Warszawa-Żoliborz', region: 'województwo mazowieckie', wiki: 'http://pl.wikipedia.org/wiki/%C5%BBoliborz'},
    {code: 'WL', name: 'Legionowo', region: 'województwo mazowieckie', wiki: 'http://pl.wikipedia.org/wiki/Legionowo'},
    {code: 'WZ', name: 'Warszawa-Zachód', region: 'województwo mazowieckie', wiki: 'http://pl.wikipedia.org/wiki/Warszawa'},
    {code: 'WBR', name: 'Białobrzegi', region: 'województwo mazowieckie', wiki: 'http://pl.wikipedia.org/wiki/Bia%C5%82obrzegi'},
    {code: 'WSC', name: 'Sochaczew', region: 'województwo mazowieckie', wiki: 'http://pl.wikipedia.org/wiki/Sochaczew'},
    {code: 'WCI', name: 'Ciechanów', region: 'województwo mazowieckie', wiki: 'http://pl.wikipedia.org/wiki/Ciechan%C3%B3w'},
    {code: 'WSE', name: 'Sierpc', region: 'województwo mazowieckie', wiki: 'http://pl.wikipedia.org/wiki/Sierpc'},
    {code: 'WGM', name: 'Grodzisk', region: 'województwo mazowieckie', wiki: 'http://pl.wikipedia.org/wiki/Grodzisk_Mazowiecki'},
    {code: 'WSI', name: 'Siedlce powiat', region: 'województwo mazowieckie', wiki: 'http://pl.wikipedia.org/wiki/Powiat_siedlecki'},
    {code: 'WGR', name: 'Grójec', region: 'województwo mazowieckie', wiki: 'http://pl.wikipedia.org/wiki/Gr%C3%B3jec'},
    {code: 'WSK', name: 'Sokołów Podlaski', region: 'województwo mazowieckie', wiki: 'http://pl.wikipedia.org/wiki/Soko%C5%82%C3%B3w_Podlaski'},
    {code: 'WGS', name: 'Gostynin', region: 'województwo mazowieckie', wiki: 'http://pl.wikipedia.org/wiki/Gostynin'},
    {code: 'WSZ', name: 'Szydłowiec', region: 'województwo mazowieckie', wiki: 'http://pl.wikipedia.org/wiki/Szyd%C5%82owiec'},
    {code: 'WKZ', name: 'Kozienice', region: 'województwo mazowieckie', wiki: 'http://pl.wikipedia.org/wiki/Kozienice'},
    {code: 'WW..A', name: 'Warszawa-Rembertów', region: 'województwo mazowieckie', wiki: 'http://pl.wikipedia.org/wiki/Rembert%C3%B3w'},
    {code: 'WLI', name: 'Lipsko', region: 'województwo mazowieckie', wiki: 'http://pl.wikipedia.org/wiki/Lipsko'},
    {code: 'WW..F', name: 'Warszawa-Wilanów', region: 'województwo mazowieckie', wiki: 'http://pl.wikipedia.org/wiki/Wilan%C3%B3w'},
    {code: 'WLS', name: 'Łosice', region: 'województwo mazowieckie', wiki: 'http://pl.wikipedia.org/wiki/%C5%81osice'},
    {code: 'WW..G', name: 'Warszawa-Wilanów', region: 'województwo mazowieckie', wiki: 'http://pl.wikipedia.org/wiki/Wilan%C3%B3w'},
    {code: 'WMA', name: 'Maków Mazowiecki', region: 'województwo mazowieckie', wiki: 'http://pl.wikipedia.org/wiki/Mak%C3%B3w_Mazowiecki'},
    {code: 'WW..H', name: 'Warszawa-Wilanów', region: 'województwo mazowieckie', wiki: 'http://pl.wikipedia.org/wiki/Wilan%C3%B3w'},
    {code: 'WML', name: 'Mława', region: 'województwo mazowieckie', wiki: 'http://pl.wikipedia.org/wiki/M%C5%82awa'},
    {code: 'WW..J', name: 'Warszawa-Wilanów', region: 'województwo mazowieckie', wiki: 'http://pl.wikipedia.org/wiki/Wilan%C3%B3w'},
    {code: 'WND', name: 'Nowy Dwór Mazowiecki', region: 'województwo mazowieckie', wiki: 'http://pl.wikipedia.org/wiki/Nowy_Dw%C3%B3r_Mazowiecki'},
    {code: 'WW..K', name: 'Warszawa-Włochy', region: 'województwo mazowieckie', wiki: 'http://pl.wikipedia.org/wiki/W%C5%82ochy_(Warszawa)'},
    {code: 'WOR', name: 'Ostrów Mazowiecka', region: 'województwo mazowieckie', wiki: 'http://pl.wikipedia.org/wiki/Ostr%C3%B3w_Mazowiecka'},
    {code: 'WW..L', name: 'Warszawa-Włochy', region: 'województwo mazowieckie', wiki: 'http://pl.wikipedia.org/wiki/W%C5%82ochy_(Warszawa)'},
    {code: 'WOS', name: 'Ostrołęka powiat', region: 'województwo mazowieckie', wiki: 'http://pl.wikipedia.org/wiki/Powiat_ostro%C5%82%C4%99cki'},
    {code: 'WW..M', name: 'Warszawa-Włochy', region: 'województwo mazowieckie', wiki: 'http://pl.wikipedia.org/wiki/W%C5%82ochy_(Warszawa)'},
    {code: 'WOT', name: 'Otwock', region: 'województwo mazowieckie', wiki: 'http://pl.wikipedia.org/wiki/Otwock'},
    {code: 'WW..N', name: 'Warszawa-Włochy', region: 'województwo mazowieckie', wiki: 'http://pl.wikipedia.org/wiki/W%C5%82ochy_(Warszawa)'},
    {code: 'WPI', name: 'Piaseczno', region: 'województwo mazowieckie', wiki: 'http://pl.wikipedia.org/wiki/Piaseczno'},
    {code: 'WW..V', name: 'Warszawa-Włochy', region: 'województwo mazowieckie', wiki: 'http://pl.wikipedia.org/wiki/W%C5%82ochy_(Warszawa)'},
    {code: 'WPL', name: 'Płock powiat', region: 'województwo mazowieckie', wiki: 'http://pl.wikipedia.org/wiki/Powiat_p%C5%82ocki'},
    {code: 'WW..W', name: 'Warszawa-Wilanów', region: 'województwo mazowieckie', wiki: 'http://pl.wikipedia.org/wiki/Wilan%C3%B3w'},
    {code: 'WPN', name: 'Płońsk', region: 'województwo mazowieckie', wiki: 'http://pl.wikipedia.org/wiki/P%C5%82o%C5%84sk'},
    {code: 'WWE', name: 'Węgrów', region: 'województwo mazowieckie', wiki: 'http://pl.wikipedia.org/wiki/W%C4%99gr%C3%B3w'},
    {code: 'WPR', name: 'Pruszków', region: 'województwo mazowieckie', wiki: 'http://pl.wikipedia.org/wiki/Pruszk%C3%B3w'},
    {code: 'WWL', name: 'Wołomin', region: 'województwo mazowieckie', wiki: 'http://pl.wikipedia.org/wiki/Wo%C5%82omin'},
    {code: 'WPU', name: 'Pułtusk', region: 'województwo mazowieckie', wiki: 'http://pl.wikipedia.org/wiki/Pu%C5%82tusk'},
    {code: 'WWY', name: 'Wyszków', region: 'województwo mazowieckie', wiki: 'http://pl.wikipedia.org/wiki/Wyszk%C3%B3w'},
    {code: 'WPY', name: 'Przysucha', region: 'województwo mazowieckie', wiki: 'http://pl.wikipedia.org/wiki/Przysucha'},
    {code: 'WZU', name: 'Żuromin', region: 'województwo mazowieckie', wiki: 'http://pl.wikipedia.org/wiki/%C5%BBuromin'},
    {code: 'WPZ', name: 'Przasnysz', region: 'województwo mazowieckie', wiki: 'http://pl.wikipedia.org/wiki/Przasnysz'},
    {code: 'WZY', name: 'Żyrardów', region: 'województwo mazowieckie', wiki: 'http://pl.wikipedia.org/wiki/%C5%BByrard%C3%B3w'},
    {code: 'WRA', name: 'Radom powiat', region: 'województwo mazowieckie', wiki: 'http://pl.wikipedia.org/wiki/Powiat_radomski'},
    {code: 'WZW', name: 'Zwoleń', region: 'województwo mazowieckie', wiki: 'http://pl.wikipedia.org/wiki/Zwole%C5%84'},
    {code: 'ZK', name: 'Koszalin miasto', region: 'województwo zachodniopomorskie', wiki: 'http://pl.wikipedia.org/wiki/Koszalin'},
    {code: 'ZLO', name: 'Łobez', region: 'województwo zachodniopomorskie', wiki: 'http://pl.wikipedia.org/wiki/%C5%81obez'},
    {code: 'ZS', name: 'Szczecin', region: 'województwo zachodniopomorskie', isCapital: 'capital', wiki: 'http://pl.wikipedia.org/wiki/Szczecin'},
    {code: 'ZMY', name: 'Myślibórz', region: 'województwo zachodniopomorskie', wiki: 'http://pl.wikipedia.org/wiki/My%C5%9Blib%C3%B3rz'},
    {code: 'ZBI', name: 'Białogard', region: 'województwo zachodniopomorskie', wiki: 'http://pl.wikipedia.org/wiki/Bia%C5%82ogard'},
    {code: 'ZPL', name: 'Police', region: 'województwo zachodniopomorskie', wiki: 'http://pl.wikipedia.org/wiki/Police'},
    {code: 'ZCH', name: 'Choszczno', region: 'województwo zachodniopomorskie', wiki: 'http://pl.wikipedia.org/wiki/Choszczno'},
    {code: 'ZPY', name: 'Pyrzyce', region: 'województwo zachodniopomorskie', wiki: 'http://pl.wikipedia.org/wiki/Pyrzyce'},
    {code: 'ZDR', name: 'Drawsko', region: 'województwo zachodniopomorskie', wiki: 'http://pl.wikipedia.org/wiki/Drawsko_Pomorskie'},
    {code: 'ZSD', name: 'Świdwin', region: 'województwo zachodniopomorskie', wiki: 'http://pl.wikipedia.org/wiki/%C5%9Awidwin'},
    {code: 'ZGL', name: 'Goleniów', region: 'województwo zachodniopomorskie', wiki: 'http://pl.wikipedia.org/wiki/Goleni%C3%B3w'},
    {code: 'ZSL', name: 'Sławno', region: 'województwo zachodniopomorskie', wiki: 'http://pl.wikipedia.org/wiki/S%C5%82awno'},
    {code: 'ZGR', name: 'Gryfino', region: 'województwo zachodniopomorskie', wiki: 'http://pl.wikipedia.org/wiki/Gryfino'},
    {code: 'ZST', name: 'Stargard Szczeciński', region: 'województwo zachodniopomorskie', wiki: 'http://pl.wikipedia.org/wiki/Stargard_Szczeci%C5%84ski'},
    {code: 'ZGY', name: 'Gryfice', region: 'województwo zachodniopomorskie', wiki: 'http://pl.wikipedia.org/wiki/Gryfice'},
    {code: 'ZSW', name: 'Świnoujście', region: 'województwo zachodniopomorskie', wiki: 'http://pl.wikipedia.org/wiki/%C5%9Awinouj%C5%9Bcie'},
    {code: 'ZKA', name: 'Kamień Pomorski', region: 'województwo zachodniopomorskie', wiki: 'http://pl.wikipedia.org/wiki/Kamie%C5%84_Pomorski'},
    {code: 'ZSZ', name: 'Szczecinek', region: 'województwo zachodniopomorskie', wiki: 'http://pl.wikipedia.org/wiki/Szczecinek'},
    {code: 'ZKL', name: 'Kołobrzeg', region: 'województwo zachodniopomorskie', wiki: 'http://pl.wikipedia.org/wiki/Ko%C5%82obrzeg'},
    {code: 'ZWA', name: 'Wałcz', region: 'województwo zachodniopomorskie', wiki: 'http://pl.wikipedia.org/wiki/Wa%C5%82cz'},
    {code: 'ZKO', name: 'Koszalin powiat', region: 'województwo zachodniopomorskie', wiki: 'http://pl.wikipedia.org/wiki/Powiat_koszali%C5%84ski'},
    
    {code: 'CS', name: 'Świecie', region: 'województwo kujawsko-pomorskie', wiki: 'http://pl.wikipedia.org/wiki/%C5%9Awiecie'},
    {code: 'NOG', name: 'Olecko (do 2002r.)', region: 'województwo warmińsko-mazurskie', wiki: 'http://pl.wikipedia.org/wiki/Olecko'},
    {code: 'STY', name: 'Tychy (powiat do 2002r.)', region: 'województwo śląskie', wiki: 'http://pl.wikipedia.org/wiki/Tychy'},
    {code: 'WV', name: 'Wołomin (od 2003r.)', region: 'województwo mazowieckie', wiki: 'http://pl.wikipedia.org/wiki/Tychy'},

    {code: 'HB', name: 'Wojska MSWiA (do 2003r.)', isSpecial: true},
    {code: 'HC', name: 'Izba Celna', isSpecial: true},
    {code: 'HK', name: 'Agencja Bezpieczeństwa Wewnętrznego i Agencja Wywiadu', isSpecial: true},
    {code: 'HM', name: 'Służba Wywiadu Wojskowego i Służba Kontrwywiadu Wojskowego', isSpecial: true},
    {code: 'HP', name: 'Policja', isSpecial: true},
    {code: 'HS', name: 'Kontrola Skarbowa', isSpecial: true},
    {code: 'HW', name: 'Straż Graniczna', isSpecial: true},
    {code: 'UA', name: 'Samochód osobowy lub terenowy sił zbrojnych', isSpecial: true},
    {code: 'UB', name: 'Transporter opancerzony sił zbrojnych', isSpecial: true},
    {code: 'UC', name: 'Samochód dostawczy sił zbrojnych', isSpecial: true},
    {code: 'UD', name: 'Autobus sił zbrojnych', isSpecial: true},
    {code: 'UE', name: 'Samochód ciężarowy sił zbrojnych', isSpecial: true},
    {code: 'UG', name: 'Pojazd specjalistyczny sił zbrojnych', isSpecial: true},
    {code: 'UIUJ', name: 'Przyczepa sił zbrojnych', isSpecial: true},
    {code: 'UxxxxxT', name: 'Pojazd gąsienicowy sił zbrojnych', isSpecial: true},
    {code: 'HPA', name: 'Komenda Główna', isSpecial: true},
    {code: 'HPB', name: 'Dolnośląska Komenda Wojewódzka', isSpecial: true},
    {code: 'HPC', name: 'Kujawsko-Pomorska Komenda Wojewódzka', isSpecial: true},
    {code: 'HPD', name: 'Lubelska Komenda Wojewódzka', isSpecial: true},
    {code: 'HPE', name: 'Lubuska Komenda Wojewódzka', isSpecial: true},
    {code: 'HPF', name: 'Łódzka Komenda Wojewódzka', isSpecial: true},
    {code: 'HPG', name: 'Małopolska Komenda Wojewódzka', isSpecial: true},
    {code: 'HPH', name: 'Mazowiecka Komenda Wojewódzka', isSpecial: true},
    {code: 'HPJ', name: 'Opolska Komenda Wojewódzka', isSpecial: true},
    {code: 'HPK', name: 'Podkarpacka Komenda Wojewódzka', isSpecial: true},
    {code: 'HPL A001-C999HPL 01AA-99CZ', name: 'Wyższa Szkoła Policji w Szczytnie', isSpecial: true},
    {code: 'HPL D001-E999HPL 01DA-99EZ', name: 'Szkoła Policji w Pile', isSpecial: true},
    {code: 'HPL F001-G999HPL 01FA-99GZ', name: 'Szkoła Policji w Słupsku', isSpecial: true},
    {code: 'HPL H001-J999HPL 01HA-99JZ', name: 'Centrum Szkolenia Policji w Legionowie', isSpecial: true},
    {code: 'HPL K001-L999HPL 01KA-99LZ', name: 'Szkoła Policji w Katowicach', isSpecial: true},
    {code: 'HPM', name: 'Podlaska Komenda Wojewódzka', isSpecial: true},
    {code: 'HPN', name: 'Pomorska Komenda Wojewódzka', isSpecial: true},
    {code: 'HPP', name: 'Śląska Komenda Wojewódzka', isSpecial: true},
    {code: 'HPS', name: 'Świętokrzyska Komenda Wojewódzka', isSpecial: true},
    {code: 'HPT', name: 'Warmińsko-Mazurska Komenda Wojewódzka', isSpecial: true},
    {code: 'HPU', name: 'Wielkopolska Komenda Wojewódzka', isSpecial: true},
    {code: 'HPW', name: 'Zachodniopomorska Komenda Wojewódzka', isSpecial: true},
    {code: 'HPZ', name: 'Komenda Stołeczna Policji', isSpecial: true},
    {code: 'HCA', name: 'Izba Celna w Olsztynie', isSpecial: true},
    {code: 'HCB', name: 'Izba Celna w Białymstoku', isSpecial: true},
    {code: 'HCC', name: 'Izba Celna w Białej Podlaskiej', isSpecial: true},
    {code: 'HCD', name: 'Izba Celna w Przemyślu', isSpecial: true},
    {code: 'HCE', name: 'Izba Celna w Krakowie', isSpecial: true},
    {code: 'HCF', name: 'Izba Celna w Katowicach', isSpecial: true},
    {code: 'HCG', name: 'Izba Celna we Wrocławiu', isSpecial: true},
    {code: 'HCH', name: 'Izba Celna w Rzepinie', isSpecial: true},
    {code: 'HCJ', name: 'Izba Celna w Szczecinie', isSpecial: true},
    {code: 'HCK', name: 'Izba Celna w Gdyni', isSpecial: true},
    {code: 'HCL', name: 'Izba Celna w Warszawie', isSpecial: true},
    {code: 'HCM', name: 'Izba Celna w Toruniu', isSpecial: true},
    {code: 'HCN', name: 'Izba Celna w Łodzi', isSpecial: true},
    {code: 'HCO', name: 'Izba Celna w Poznaniu', isSpecial: true},
    {code: 'HCP', name: 'Izba Celna w Opolu', isSpecial: true},
    {code: 'HCR', name: 'Izba Celna w Kielcach', isSpecial: true},
    {code: 'HSB', name: 'Kontrola skarbowa', region: 'województwo podlaskie', isSpecial: true},
    {code: 'HSC', name: 'Kontrola skarbowa', region: 'województwo kujawsko-pomorskie', isSpecial: true},
    {code: 'HSD', name: 'Kontrola skarbowa', region: 'województwo dolnośląskie', isSpecial: true},
    {code: 'HSE', name: 'Kontrola skarbowa', region: 'województwo łódzkie', isSpecial: true},
    {code: 'HSF', name: 'Kontrola skarbowa', region: 'województwo lubuskie', isSpecial: true},
    {code: 'HSG', name: 'Kontrola skarbowa', region: 'województwo pomorskie', isSpecial: true},
    {code: 'HSK', name: 'Kontrola skarbowa', region: 'województwo małopolskie', isSpecial: true},
    {code: 'HSL', name: 'Kontrola skarbowa', region: 'województwo lubelskie', isSpecial: true},
    {code: 'HSN', name: 'Kontrola skarbowa', region: 'województwo warmińsko-mazurskie', isSpecial: true},
    {code: 'HSO', name: 'Kontrola skarbowa', region: 'województwo opolskie', isSpecial: true},
    {code: 'HSP', name: 'Kontrola skarbowa', region: 'województwo wielkopolskie', isSpecial: true},
    {code: 'HSR', name: 'Kontrola skarbowa', region: 'województwo podkarpackie', isSpecial: true},
    {code: 'HSS', name: 'Kontrola skarbowa', region: 'województwo śląskie', isSpecial: true},
    {code: 'HST', name: 'Kontrola skarbowa', region: 'województwo świętokrzyskie', isSpecial: true},
    {code: 'HSW', name: 'Kontrola skarbowa', region: 'województwo mazowieckie', isSpecial: true},
    {code: 'HSZ', name: 'Kontrola skarbowa', region: 'województwo zachodniopomorskie', isSpecial: true}
    ];
}
PlatesListCtrl.inject = ['$scope'];

